### ISSUE TITLE
"Cannot GET /" in Browser

### ISSUE THREAD

**Issue by motherboard1999** [Angestoepselt/reversy2#4]
Browser Error: `Cannot GET /`
NPM Error: 
`➜  frontend git:(master) ✗ npm start

> reversy2Frontend@1.0.0 start /Users/f.helmerich/Git/reversy2/frontend
> cross-env ENABLE_ESLINT=false node build/dev-server.js

(node:7419) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

 ERROR  Failed to compile with 5 errors                                 09:21:31

 error  in ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.eot

Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (/Users/f.helmerich/Git/reversy2/frontend/node_modules/file-loader/index.js:13:28)
    at Object.loader (/Users/f.helmerich/Git/reversy2/frontend/node_modules/url-loader/dist/index.js:76:19)

 @ ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css 6:4445-4497 6:4520-4572
 @ ./~/bootstrap/dist/css/bootstrap.css
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2

Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (/Users/f.helmerich/Git/reversy2/frontend/node_modules/file-loader/index.js:13:28)
    at Object.loader (/Users/f.helmerich/Git/reversy2/frontend/node_modules/url-loader/dist/index.js:76:19)

 @ ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css 6:4622-4676
 @ ./~/bootstrap/dist/css/bootstrap.css
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.woff

Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (/Users/f.helmerich/Git/reversy2/frontend/node_modules/file-loader/index.js:13:28)
    at Object.loader (/Users/f.helmerich/Git/reversy2/frontend/node_modules/url-loader/dist/index.js:76:19)

 @ ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css 6:4707-4760
 @ ./~/bootstrap/dist/css/bootstrap.css
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf

Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (/Users/f.helmerich/Git/reversy2/frontend/node_modules/file-loader/index.js:13:28)
    at Object.loader (/Users/f.helmerich/Git/reversy2/frontend/node_modules/url-loader/dist/index.js:76:19)

 @ ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css 6:4790-4842
 @ ./~/bootstrap/dist/css/bootstrap.css
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.svg

Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
    at Object.module.exports (/Users/f.helmerich/Git/reversy2/frontend/node_modules/file-loader/index.js:13:28)
    at Object.loader (/Users/f.helmerich/Git/reversy2/frontend/node_modules/url-loader/dist/index.js:76:19)

 @ ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css 6:4876-4928
 @ ./~/bootstrap/dist/css/bootstrap.css
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080`

**Comment by blitze299** [comment]
try to update package like in #5
